name:                expert-robot
version:             0.1.0.0
homepage:            'https://github.com/bergey/expert-robot#readme'
license:             BSD3
license-file:        LICENSE
author:              Daniel Bergey
maintainer:          bergey@teallabs.org
copyright:           BSD3

library:
    source-dirs: ./src
    build-tools: alex

tests:
  expert-robot:
    source-dirs:      test
    main:             Main.hs
    dependencies:
      - expert-robot

dependencies:
    - base
    - array
    - bytestring
    - containers
    - text
