name:                expert-robot
version:             0.1.0.0
homepage:            'https://github.com/bergey/expert-robot#readme'
license:             BSD3
license-file:        LICENSE
author:              Daniel Bergey
maintainer:          bergey@teallabs.org
copyright:           BSD3

executables:
  expert-robot:
    source-dirs:      src
    main:             Main.hs
    build-tools: alex

dependencies:
    - base
    - array
    - bytestring
    - containers
    - text
